### ISSUE TITLE
After Featured image is added in Customizer, error displays in WP Admin Featured image

### ISSUE THREAD

**Issue by alcurrie** [xwp/wp-customize-posts#108]
**Test Steps**
Navigate to `{removed link}` and login
Click on Pages then >Add new page - WP only - Featured image
View Featured image box
_**Expected:**_
The featured image interface in WP Admin displays without error and works to upload a featured image

**Actual:**
On navigating to a new page, (even prior to saving the page) the Featured image box displays with error message - Warning: Missing argument 3 for WP_Customize_Featured_Image_Controller::filter_admin_post_thumbnail_html() in /srv/bindings/327e7c8b5e2b477ba002a93d24b46535/code/wp-content/plugins/customize-posts/php/class-wp-customize-featured-image-controller.php on line 189

![newpagefeaturedimageerror](https://cloud.githubusercontent.com/assets/18579988/14840933/f24d9972-0c06-11e6-9846-443e2068bb60.png)

NB: the featured image functionality was working in WP Admin, prior to the customizer update to add the featured image in customizer.

**Comment by alcurrie** [comment]
@westonruter  - as discussed, the featured image functionality was working in WP admin for the site tested, prior to the deployment of the new Featured image in Customizer.

**Comment by valendesigns** [comment]
@alcurrie It appears the third parameter `$thumbnail_id` was added to Core in the last 2 weeks, which means this plugin is now dependent on 4.6. However, we can remove this dependency and be 4.5 compatible by setting a default value of `-1`. I'm working up a PR now.

**Comment by valendesigns** [comment]
Actually, that appears to have unintended side effects. I'll keep looking into this issue though.

**Comment by westonruter** [comment]
How about a default value of `null` and if is `null` to then call `get_post_thumbnail_id()` for the given post?

**Comment by valendesigns** [comment]
@westonruter That's what I've been playing around with. However, there appears to be a secondary issue where the preview keeps refreshing over and over again when the featured image is not set and you click "Preview Changes" from the edit-post page, but not when you enter the normal Customizer.

**Comment by valendesigns** [comment]
I think I've got a solution, I'm just testing it in both 4.5 & 4.6

**Comment by westonruter** [comment]
Regarding the constant refreshing issue, I think this is due to this code in `edit-post-preview-admin-featured-image.js`:

```
	var metaKey = '_thumbnail_id', inputSelector = '#_thumbnail_id';

	// Handle syncing settings from edit post admin page to Customizer.
	wp.customize.bind( 'settings-from-edit-post-screen', function( settings ) {
		var settingId = EditPostPreviewAdmin.getPostMetaSettingId( metaKey );
		settings[ settingId ] = parseInt( $( inputSelector ).val(), 10 );
	} );
```

Specifically `parseInt( $( inputSelector ).val(), 10 )` is wrong now. When a featured image is removed, the value stored in the Customizer setting should be `''` not `-1`.
