### ISSUE TITLE
Customizer Pane Collapse Issue

### ISSUE THREAD

**Issue by ahmadawais** [xwp/wp-customize-posts#125]
Once Collapsed, there is no way to access Customizer again. When I edit the content and collapse the Customizer pane there is no way for me to access it again.  I am sure this is not an intentional behavior.

![](https://i.imgur.com/hsnDnMV.png)

**Comment by westonruter** [comment]
@ahmadawais is this not a duplicate of #44?

**Comment by ahmadawais** [comment]
@westonruter Yup it is. I thought the old ticket was resolved. Apparently it isn't. Closing this one.
