### ISSUE TITLE
removed wpautop filter not persistent in Customizer Editor

### ISSUE THREAD

**Issue by bsusala** [xwp/wp-customize-posts#127]
Using WP Edit Plugin for editing html in Text Mode in Edit Post/Page, with the setting disable wpautop, globally and/or per Page/Post.

But when editing the Page/Post in Customizer, it sanitizes the content, making the process unusable.

**Comment by westonruter** [comment]
@bsusala to clarify, the issue is that Customize Posts forces the visual editor to be used initially as opposed to the text editor, and so when switching from visual to text the content is corrupted?

**Comment by westonruter** [comment]
@bsusala From your [support forum comment](https://wordpress.org/support/topic/add-post-2?replies=4#post-8359563):

> This, and the possibility to remove wpautop filter, will force me to almost never quit Customizer, making it a de facto web editor.
>
> So, I was about to open another thread, but since I mentioned above, here it is:
>
> I use WP Edit for code editing style, and also for being able to manage wpautop. However, after I try to edit the page in Customizer, the Editor sanitizes the content, making the process useless. Is there a way to preserve the WP Edit setting, or (if you ask me, since Text Tab is basically html/code editing) to automatically remove wpautop globally.
> 
> I understand this must accomodate the general WP behaviour, which is disputable in regard to wpautop. One way may be a checkbox near the Open Editor button to allow/deny wpautop?

**Comment by bsusala** [comment]
The exact behaviour is:
- Text in Page is edited and added <p> tags with WP Edit and wpautop checkbox checked (disables wpautop, this is a WP Edit feature, available per Page/Post)
- Customizer > Pages > Click on Page; all ok, text formatted as it should
- click Open Editor, Editor opensup, format still ok
- BUT as soon as I click inside the window, be it Visual, or Text, content is sanitized

**Comment by westonruter** [comment]
OK, I didn't realize you were referring to a plugin called “[WP Edit](https://wordpress.org/plugins/wp-edit/)”.

**Comment by bsusala** [comment]
@westonruter sorry, yes, it's the Plugin. But this behaviour is also present if I remove the filter through functions.php, I just mentioned the actual environment (if it's of any worth).

**Comment by westonruter** [comment]
@bsusala It sounds like the issue is rooted in [this line](https://github.com/xwp/wp-customize-posts/blob/6fdb4ee205cf411f2587cc8d9f285cd9a1372d96/js/customize-post-section.js#L244):

```js
editor.setContent( wp.editor.autop( newPostData.post_content ) );
```

And the converse lines that call `wp.editor.removep()`.

I tried commenting out from `default-filters.php`:

```php
add_filter( 'the_content', 'wpautop'                           );
```

And I added two line breaks in the editor and confirmed that paragraphs weren't added on the frontend. Nevertheless, the paragraphs _were_ still automatically getting added in the normal visual editor. Is this a feature of WP Edit to disable the autop functionality in the core visual editor?

**Comment by bsusala** [comment]
Yes, it applies to any instance of core Editor, be it in Page, Post, or even every Section in GeneratePress :)

I activate by this checkbox:
![wpautop](https://cloud.githubusercontent.com/assets/7239304/14996102/ef399d10-1180-11e6-810e-acf0558b783f.jpg)

**Comment by westonruter** [comment]
@bsusala ok, so this is a plugin-specific feature that they'll need to add support for in the Customizer.

To start, they can add to `wp_edit_class::add_page()`:

```php
add_action( 'customize_controls_enqueue_scripts', array($this, 'admin_scripts') );
add_action( 'customize_controls_enqueue_scripts', array($this, 'admin_styles') );
```

But then they'll need to add a UI for toggling whether to disable `wpautop`.

**Comment by bsusala** [comment]
Ok, but just an opinion: couldn't this be something coded by YOUR plugin? It's true that WP Edit is commonplace for trying to mimic code-editors in WP, but, actually, the most important feature is that wpautop (and line numbers, okay :) ). Couldn't implement yourself that? I think will help alot, in the direction of trying to edit as much as possible in Customizer.

**Comment by westonruter** [comment]
I think it is out of scope for Customize Posts. I've personally never come across turning off `wpautop` in the editor and it's not a capability in Core without a plugin. Since Customize Posts is being developed for core merge, having special support for community plugins needs to be minimized.

**Comment by josh401** [comment]
Hi, I'm the author of WP Edit.  I have been absent a few days; but will give this issue some attention and see if we can't find a simple fix.

@bsusala, please refer to the thread on the WP forums for further info.  We will come back here once we know more about the issue.  Thank you.
