### ISSUE TITLE
Add compatibility with Custom Contact Forms

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#128]
See https://wordpress.org/support/topic/other-plugin-metashortcodes-does-not-show-in-editor

> I use Custom Contact Form Plugin, and its shortcodes on pages. Forms do not show in Customizer > Forms, and the shortcode doesn't show in Editor. 

<img width="1066" alt="customize__here_is_something_interesting___ _wordpress_develop" src="https://cloud.githubusercontent.com/assets/134745/14995166/3d5790b4-1128-11e6-8700-cd08e76a7fd4.png">

**Comment by westonruter** [comment]
@bsusala Does the screenshot ☝️ depict what you're seeing and the problem you're experiencing?

**Comment by bsusala** [comment]
No, see image:
![form](https://cloud.githubusercontent.com/assets/7239304/14995713/e225f2ba-117e-11e6-8cbb-90b163143831.jpg)

**Comment by westonruter** [comment]
@bsusala thanks. The reason why the form doesn't appear here is because of #96. Since `get_post()` is (naturally) used to obtain the form post, there is no `the_posts` filter applied and so Customize Posts doesn't “see” the post being used in the current page. 

You do see forms listed if this workaround is applied: https://github.com/tlovett1/custom-contact-forms/commit/9090be7cf6d45565e1d8e474635c298e8f0987c5

However, it doesn't add much value as is.

Here's the panel:

<img width="735" alt="forms panel" src="https://cloud.githubusercontent.com/assets/134745/14996474/0bbaf742-112f-11e6-904c-593fbdc76abe.png">

And the section:

<img width="734" alt="form-section" src="https://cloud.githubusercontent.com/assets/134745/14996468/08f9e040-112f-11e6-84ab-0ce944e1235d.png">

But, even on the admin edit post screen for forms, you can't actually edit forms in that context either, right? It seems there's no UI for form editing outside the context of the metabox that opens on the edit post screen, and so the focus should be on the “Add Form” button in the editor.

For the Forms section, I suggest adding a plugin that just prevents the Forms post type from appearing in the Customizer at all:

```php
add_action( 'wp_loaded', function() {
	$post_type_obj = get_post_type_object( 'ccf_form' );
	if ( $post_type_obj ) {
		$post_type_obj->show_in_customizer = false;
	}
} );
```

**Comment by bsusala** [comment]
Well, you are right. But UX-wise, there should be resolved the obvious "There is no form in Preview", which is not correct. Maybe changing the verbose: "There are forms, but they are editable through their original UI etc." :) Anyways, I am not so expert in forms and or plugins, so I do not know if other forms are editable in Editor, or though their plugin interfaces. So maybe keep any editable field from forms which makes sense (if any, like you did with title), and then suggest the user to go where appropiate.

**Comment by westonruter** [comment]
@bsusala the problem is that the Customize Posts isn't even aware that there are editable forms. The only way it knows about there being posts of a given post type is if they pass through the `the_posts` filter: https://github.com/xwp/wp-customize-posts/blob/6fdb4ee205cf411f2587cc8d9f285cd9a1372d96/php/class-wp-customize-posts-preview.php#L127-L147

This will be remedied when we have a way to look deeper into when `get_post()` calls are made.

@bsusala can you confirm that you do see an “Add Form” button when you open a post/page to edit in the Customizer? But that clicking this button does nothing? Adding a UI via the Forms panel would be something that Custom Contact Forms would need to add support for. Fixing the button in the editor would be something Customize Posts could add support for, or rather upstream a fix for.

**Comment by bsusala** [comment]
I can see [Add Form]. I also have another button for a plugin named Calculated Fields Form. Both are doing nothing when clicked.

**Comment by westonruter** [comment]
Merged upstream.
