### ISSUE TITLE
Allow customize_loaded_components filter to remove posts component

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#132]
Currently there is one `customize_loaded_components` filter which handles the injection of the `WP_Customize_Posts` instance into `WP_Customize_Manager`:

```php
add_filter( 'customize_loaded_components', array( $this, 'filter_customize_loaded_components' ), 100, 2 );
```

There should be another `customize_loaded_components` filter that runs earlier at priority 0 which amends `posts` to the list of components. Then the later filter can check to see of `posts` is in the array and then only instantiate `WP_Customize_Posts` if it is present.

This would allow plugins to use a more standard way to selectively disable the `posts` component.

**Comment by kienstra** [comment]
**Pull Request**

@westonruter, 
Could you please review this [pull request](https://github.com/xwp/wp-customize-posts/pull/219/files) when you have a chance? It sets a new filter `add_posts_to_customize_loaded_components`. This adds `'posts'` to the array of components in the Customizer. And `WP_Customize_Posts` is only instantiated if `'posts'` is still present. So a later filter may remove `'posts'`, to disable it.
