### ISSUE TITLE
Delete a post whilst in the Customizer

### ISSUE THREAD

**Issue by danielbachhuber** [xwp/wp-customize-posts#137]
It would be great if I could trash or delete a post whilst in the Customizer.

I recognize that this task isn't small, and will need some UX exploration, etc. before it can go to development.

**Comment by westonruter** [comment]
Definitely. This is something we'll work on after #134 is merged for adding post insertion.

**Comment by westonruter** [comment]
We'll also have the control for managing the post status (#40) which could potentially include “trash” as one of the options until a dedicated button/UI is provided for deletion.

**Comment by danielbachhuber** [comment]
> We'll also have the control for managing the post status (#40) which could potentially include “trash” as one of the options until a dedicated button/UI is provided for deletion.

Oh, huh. That kinda sucks, but could work as an interim solution.

**Comment by westonruter** [comment]
It's just a matter of the UI. Implementing trash would be simple, as it would be just setting the `post_status` for the `post` setting object to `trash`. So yeah, I don't see why a delete button and the post status dropdown couldn't be done at the same time.

**Comment by westonruter** [comment]
As for the behavior of clicking “Trash” I think it should:

1. Set the `post_status` for the `post` setting to `trash`.
2. Trigger a refresh of the previous (should happen automatically).
3. Collapse the post section for the trashed post.
4. Add a deleted style to the post section in the list of posts in the panel, perhaps with 50% opacity.
5. Upon clicking Save, the post section should be removed from the panel entirely.

**Comment by danielbachhuber** [comment]
@westonruter Did we end up with a button here, or just the status dropdown?

**Comment by westonruter** [comment]
@danielbachhuber this is being discovered in #172.
