### ISSUE TITLE
deferred invokes embedded.done before the control is actually embedded.

### ISSUE THREAD

**Issue by sayedwp** [xwp/wp-customize-posts#158]
I created a dynamic control using `wp.customize.controlConstructor.dynamic`, and I am trying to get access of the control elements when it's embedded to the customizer. So I used `control.deferred.embedded.done` which works well with the already created post however when you create a new post, it fires before the control is actually embedded into the customizer.
Please look at the code snippet below.

```js
 ;(function( api ) {
            var control, settingId, controlID, customPostType = 'trainer';
            api.section.bind( 'add', function( section ) {
                if ( section.extended( api.Posts.PostSection ) && customPostType === section.params.post_type ) {

                    controlID = 'postmeta[' + section.params.post_type + '][' + String( section.params.post_id ) + '][fieldId]';

                    control = new api.controlConstructor.dynamic( controlID, {
                        'params': {
                            section: section.id,
                            priority: 41,
                            label: "Test Label",
                            active: true,
                            setting: {
                                'defaults': controlID
                            },
                            field_type: 'text',
                            input_attrs: {
                                'data-customize-setting-link': controlID
                            }
                        }
                    });

                    control.active.set( true );
                    api.control.add( control.id, control );

                    control.deferred.embedded.done( function() {
                        /**
                         * It will give you the id of the control because its embedded
                         * However it does not give the id of the control element when you create a new post
                         * by clicking the add new post button.
                         */
                        console.log( jQuery( control.selector ).attr( 'id' ) );
                    } );

                }
            });
 })( wp.customize );
```

I am using the develop branch ( Version: 0.5.0  ) of the plugin

**Comment by valendesigns** [comment]
@sayedwp Could you verify this is still an issue in 0.6.0

**Comment by westonruter** [comment]
@sayedwp I'm curious about why this is happening because `actuallyEmbed` seems to indicate that the control will get embedded before `embedded` is resolved: https://github.com/xwp/wp-customize-posts/blob/cd4e557ac45574fd4d950faac394bd566706e49e/js/customize-dynamic-control.js#L164-L177

**Comment by sayedwp** [comment]
@valendesigns I tried that with 0.6.0 did not work.

@westonruter I think `control.deferred.embedded.resolve()` is doing its job as expected, however the problem is with `control.renderContent();`

I tried to debug it by going to customize-control.js and there is something which is puzzling me.

	renderContent: function () {
			var template,
				control = this;

			// Replace the container element's content with the control.
			if ( 0 !== $( '#tmpl-' + control.templateSelector ).length ) {
				template = wp.template( control.templateSelector );
				if ( template && control.container ) {
					control.container.html( template( control.params ) );

					if ( control.id.indexOf( '[elimination_date]' ) > -1 ) {
						console.log( control.container.html(), "It has the html" );
						console.log( control.container.attr('id'), "It also gives you id of the container" );
						console.log( control.selector, "It also has the selector id " );
						console.log( jQuery( control.selector ).html(), "Now if you use the same id to get the html, it surprisingly does not have it. " );
					}
				}
			}
		}

**Comment by westonruter** [comment]
@sayedwp the problem is this line in your sample code:

```js
console.log( jQuery( control.selector ).attr( 'id' ) );
```

It should instead be scoped to the control like this:

```js
console.log( jQuery( control.container ).find( someSelector ).attr( 'id' ) );
```

So the control may not be in the DOM yet, but there is a DOM element you can interact with.

**Comment by sayedwp** [comment]
@westonruter Yes I can interact with the element using `control.container.find( 'someSelector' )`  however shouldn't `control.deferred.embedded` be resolved after the element is actually available in the DOM like the way it does in case of existing post's sections?

**Comment by westonruter** [comment]
@sayedwp that's a good question, and I'm not 100% sure, but I think it is due to the fact that we're using dynamically-generated controls. When you add a control to a section, it is done with a `defer` to wait for all UI changes (priority changes, control/section re-assignments, etc) to be done at once instead of slamming the DOM with every change. So I think what is happening is the moment you create the control and it is embedded, it is still waiting for that defer to `reflowPaneContents` and do this logic which actually injects the control into the DOM: https://github.com/xwp/wordpress-develop/blob/ead348053b6f73b85425eaa780c6f336c0514fb3/src/wp-admin/js/customize-controls.js#L3699-L3709

In any case I think it is better to use `control.container` to keep the jQuery scoped to the control and not rely on it being accessed from outside of the controller. This keeps it encapsulated, a Shadow DOM if you will 😄

**Comment by sayedwp** [comment]
@westonruter Oh now I see, that answers my question. Perfect! Thanks (:
