### ISSUE TITLE
Trashed post section unexpectedly appears at root upon customize-save

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#164]
Defect in 0.6.0:

1. Change a post's status to trash
2. Publish
3. Collapse the Posts panel to see the root of the Customizer.
4. See the trashed post section unexpectedly appear in the root.

<img width="305" alt="trashed-post-root-section" src="https://cloud.githubusercontent.com/assets/134745/15812640/411ae508-2b6c-11e6-9422-79a20dca410a.png">

**Comment by valendesigns** [comment]
@westonruter I cannot reproduce this issue?

**Comment by westonruter** [comment]
@valendesigns it's happening for me in two separate installs. Here's a video: https://youtu.be/J_o26Lim-fU

**Comment by valendesigns** [comment]
I understand now, sorry I do see it to.
