### ISSUE TITLE
Trashed post shows published and changes status to publish if loaded again and you hit publish.

### ISSUE THREAD

**Issue by sayedtaqui** [xwp/wp-customize-posts#217]
Step-1: Trash one post and hit Save & Publish button.
Step-2: Reload the page and search for the trashed post in dropdown and open it. Or put the section id in autofocus ( `...?autofocus[section]=sectionId` )
Step-3 Hit publish/save button again ( or go to another section make changes and hit publish )

The trashed post becomes published because the status selected in post section after loading is 'publish' and not 'trash'.

**Comment by westonruter** [comment]
@sayedwp this is actually by design. When you un-trash a post it is designed to re-store the previous status and slug that were used when it was trashed previously. This follows the behavior from `wp_untrash_post()` here: https://developer.wordpress.org/reference/functions/wp_untrash_post/

You can see this behavior was specifically implemented in Customize Posts here: https://github.com/xwp/wp-customize-posts/blob/50250f165beb1192fc15aa9c5754e72b5d24d53d/php/class-wp-customize-posts.php#L1031-L1048

This being said, is there a bug here?

**Comment by sayedwp** [comment]
I see a problem with this behaviour, it can make a trashed post go publish, which was not intended by user, I will create a video explaining this later today.

**Comment by westonruter** [comment]
If they don't want it to be published, then they shouldn't be opening it from trash. If they want it to stay in the trash, then they should click “Move to trash” or change the status back to trash. Perhaps a notification added to the status control to alert the user that the status has been restored would be in order, and notifying them that if they publish now the post will be restored.

**Comment by sayedwp** [comment]
@westonruter  Here is the video
https://www.youtube.com/watch?v=kAV-1FOtSqQ

**Comment by sayedwp** [comment]
Exactly, at least adding a notification would be great, so they have some way of knowing that they are making that post published.

**Comment by westonruter** [comment]
@sayedwp thanks for that helpful video. Yeah, a notification is needed here at the very least. Something like this:

<img width="300" alt="screen shot 2016-08-15 at 12 42 26 am" src="https://cloud.githubusercontent.com/assets/134745/17658528/31aa18c2-6281-11e6-8f78-c41882b211b0.png">

Example code that ads this notification:

```js
code = 'untrashed';
postStatusControlId = 'post[post][6189][post_status]';
notification = new wp.customize.Notification( code, { 
    type: 'info', 
    message: 'This has been untrashed. If you publish changes now, this post will be published. Move back to trash to avoid this.' 
} );
wp.customize.control( postStatusControlId ).notifications.add( code, notification );
```

**Comment by westonruter** [comment]
Something else that would help here is a listing of all of the dirty changes in the current Customizer state: https://github.com/xwp/wp-customize-snapshots/issues/61

**Comment by westonruter** [comment]
Note that the notification should be added when the post is restored from trash, and the notification should be removed once the `saved` event happens or if the `post_status` switches back to `trash`.
