### ISSUE TITLE
Notifications container overlaps with post date title

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#229]
It looks like the Post Date control needs to explicitly add a `clear:both` to its `.customize-control-notifications-container` or else we can get this:

<img width="287" alt="customize__john_smithssssss_ _wordpress_develop" src="https://cloud.githubusercontent.com/assets/134745/17939730/c9efd796-69e0-11e6-9cfa-2edf63c61749.png">

**Comment by sayedwp** [comment]
@westonruter Fixed in https://github.com/xwp/wp-customize-posts/pull/230
