### ISSUE TITLE
Pages/posts not showing up in customizer

### ISSUE THREAD

**Issue by scottopolis** [xwp/wp-customize-posts#261]
WP Multisite
Customize posts network activated
WP 4.6.1
No other plugins active, twentyfifteen theme

In the customizer I go to Pages->Add new. Create page and save as published.  Refresh and go to pages, it's not there.  If I search for the pages, they are there, they just don't show up below the search box.  Same thing happens for posts.

Video: https://cl.ly/2e202E070v0v

Thanks for this awesome plugin!

**Comment by westonruter** [comment]
@scottopolis This is expected actually. Posts/pages currently only show below the search box if they are shown in the preview or if they are searched for in the search box. See #146 for work to get all posts/pages to be listed out in the panel. Is that what you're describing?

**Comment by scottopolis** [comment]
That looks like a good solution.  Just so you know, I thought the plugin was broken and pages weren't saving because they weren't displaying there, other people might think that too. Just my 2 cents.

Thanks Weston!
