### ISSUE TITLE
Plugin description links to "obselete" Customize Setting Validation

### ISSUE THREAD

**Issue by hearvox** [xwp/wp-customize-posts#323]
In your plugin's Description (in `customize-posts.php`), this might need updating:
>Works best in conjunction with the <a href="https://wordpress.org/plugins/customize-setting-validation/">Customize Setting Validation</a> plugin.

But the Customize Setting Validation page says:
>Notice: The Customize Setting Validation plugin is obsolete. It was committed during the 4.6 release cycle in r37476.

**Comment by westonruter** [comment]
Good point. That reference should be removed.
