### ISSUE TITLE
Adding custom postmeta controls

### ISSUE THREAD

**Issue by thadallender** [xwp/wp-customize-posts#330]
Hey all, very excited about this plugin! Seems like it will _also_ help to solve some of the on-boarding issues that new WP users face when getting started.

Anyway, I'm looking for some docs/guidance on how to add new custom controls for postmeta. I've looked at issue #224, but I'm looking to take it one-step further and add my own custom controls.

I'm looking to create an "Upload" button that triggers the media dialog/frame, which will then save multiple selected attachment ID's to a hidden input field (postmeta). I guess in some ways it would function similar to the featured image control. My plan is to:

1. Filter customize_loaded_components and include my custom controller PHP class.
2. Enqueue my customizer pane and preview scripts.
3. Extend api.MediaControl to allow selections of multiple attachment ids.
4. After selection, save attachment ids to a single hidden input field.
5. After selection, show thumbnails of all attachment ids above the Upload button.

In theory, am I on the right path?

Any guidance on the above (and especially regarding how to accomplish 4 & 5 using Customize Posts) is greatly appreciated.

**Comment by westonruter** [comment]
@thadallender You can also refer to how Customize Posts implements the featured image and page template controls for how to create controls that manipulate postmeta. 

As for a control that allows you to select multiple attachments, I think actually you may want to check out this Image Gallery Control that @miina has put together: https://make.xwp.co/2016/08/12/image-gallery-control-for-the-customizer/

So then all you need to do is register your postmeta setting as being an array of attachment IDs and associate that control with the setting. There would not be any need to hack with hidden fields. The control would write the IDs directly into the setting without using hidden inputs as a proxy.

**Comment by jeffpaul** [comment]
@thadallender any updates on your review of the Image Gallery Control referenced above?

**Comment by thadallender** [comment]
@jeffpaul Yes, we got things working. I've attached a screenshot of the customizer with our gallery UI. I need to button up the code and then we'll share it here for so others can learn from it.

![gallery-ui](https://cloud.githubusercontent.com/assets/302884/22300936/232f89ca-e2f7-11e6-955f-429b8499885c.png)

**Comment by jeffpaul** [comment]
@thadallender that looks pretty great! Were you able to leverage what @miina had built or did you go down a different path? Either way, looking forward to when you can share your approach/code!

**Comment by thadallender** [comment]
We referenced the Image Gallery Control by @miina for media frame and then added additional controls to help with drag/drop sorting. It came out nice! Not sure if we'll be including it into our project or not. Either way, thanks @westonruter and @miina for the guidance! We'll share as soon as we finish our project. Thanks for reaching out @jeffpaul
