### ISSUE TITLE
Taxonomies and Custom Post-Meta not in Customizer

### ISSUE THREAD

**Issue by abayomiabayomi** [xwp/wp-customize-posts#370]
I really love this plugin but im a bit bothered that in the customizer - posts and pages taxonomies(categories and tags) dont display.
For example, i have 5 custom post -types with their respective custom post-meta as well as custom taxonomies - i dont see them too in the customizer.

Can anybody help with a fix on this issue? I would love to have Custom Post types-Post Meta and Custom Taxonomies display in the customizer.

**Comment by westonruter** [comment]
@abayomiabayomi Thanks for the input.

Yes, being able to select categories, tags, and other custom taxonomy terms is an outstanding feature that needs to be implemented. Please see #58. Work has been done for post formats specifically (#59) and is pending in a pull request (#362).

However, postmeta are fully supported now. The thing is that metaboxes registered for the edit post screen will not just automatically appear in the Customizer. The edit post screen is a PHP-driven environment whereas the Customizer is JS-based, and metaboxes currently need to be re-implemented. This is currently a challenge facing Gutenberg as well. To implement your custom postmeta, I suggest looking at the Featured Image and Page Template examples in this plugin. You can also refer to this single-file minimal example that shows how to add a custom postmeta: https://gist.github.com/westonruter/f8473159e48fbacbef9dcd6498155846

For more, see #224.
