### ISSUE TITLE
Add post status dropdown selection control and preview

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#40]
When opening a draft post in the Customizer, it would be ideal to be able to make changes and then _publish_ the post from there. For example in a workflow to preview how changes to a title wraps: https://youtu.be/sXu2pA42J88

As part of this, we can also implement the Trash button (#137) alongside the post status dropdown.

**Comment by lukecarbis** [comment]
Should this also include Visibility? i.e. Password / Public / Private / Scheduled, etc?

**Comment by westonruter** [comment]
@lukecarbis yes. Future would be implied by a `publish` status and setting a future date #53/#56. Or rather, if the date is set in the future, the `publish` option would not be available but only `future`, and vice-versa.

**Comment by westonruter** [comment]
For `post_status`, there should be a new `post_field` partial that has the behavior of doing a refresh for every change. There should not be any selective refresh aspect for changes to this field.
