### ISSUE TITLE
Implement date/time picker for publish date

### ISSUE THREAD

**Issue by ahmadawais** [xwp/wp-customize-posts#53]
Published date input can use the type="date"

I would have submitted a PR but looks like the new version doesn't contain this date input meta only W.org version does.

— We can use `type="date"` here (In the old W.org repo version)

![Image](https://i.imgur.com/JmlnQd4.png)

**Comment by westonruter** [comment]
@ahmadawais the plugin was recently updated on W.org as well. So there is not currently a datetime field.

I worked quite a bit trying to get a `date` input working for [Customize REST Resources](https://github.com/xwp/wp-customize-rest-resources) plugin, but without much success.

Also, there is the issue that they just aren't yet support (or supported very well) by browsers: http://caniuse.com/#feat=input-datetime

**Comment by ahmadawais** [comment]
@westonruter  I see. I will read the source for ` Customize REST Resources ` and will see if anything is possible. Would it be taking things too far if I recommend `[select2.js](https://select2.github.io/)`? It has been battle-tested. Maybe we could use that for select boxes and then Datepicker via jQuery UII.

**Comment by westonruter** [comment]
Done in #202
