### ISSUE TITLE
Implement control and preview for post_date

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#56]
To start, this can be a simple text field containing the date. For specifics regarding the UI, see #53.

Care will need to be taken when modifying the date time so that the post will continue to appear in the preview when the date is in the future. Also, it would seem logical that changing the date should result in the order of the posts changing in the preview.

There may need to be a partial registered for the display of a post date. If not, then the entire content `part` will need to be refreshed (#36).

**Comment by aristath** [comment]
We could also use `jquery-ui-datepicker` since WP already includes it...

**Comment by westonruter** [comment]
There is this: https://github.com/xwp/wp-jquery-ui-datepicker-skins

However, a problem is that there is no time selection as part of the date picker.

**Comment by aristath** [comment]
nice! I hadn't seen those styles...
How about something like this? http://jsfiddle.net/arunu/5qkt8e06/
both date &time combined.

**Comment by westonruter** [comment]
Yeah, that could work. It would need to validate that the time is in the valid format, and it would also need to keep track of the time that was set before the update to prevent clobbering it with each change to the date.

**Comment by aristath** [comment]
I started working on a datetime control for the customizer.
I got the datepicker to work fine, no issues there.
Now the dilemma is this:
Should we have both date & time in the same input element?
Or would it be better to have an input for the date and then a separate input element for the time?

If we have them both in the same input field, the result will be similar to http://jsfiddle.net/arunu/5qkt8e06/
pros: easier to develop
cons: not that pretty, harder to sanitize.

If we have them as 2 separate fields, we can use the datepicker for the date (we can even have the datepicker expanded and hide the textfield), and then next to it or below it have a smaller textfield to select the time.
We can even use jQuery spinner (also included in WP Core) and do something like this: https://jqueryui.com/spinner/#time
We can then sanitize/validate their values separately via JS and then combine them the way we want them internally from the control's JS.
pros: easier to sanitize, prettier
cons: harder to develop but if we want it I'd be more than happy to do it. I'm halfway there anyway... 

Thoughts?

**Comment by westonruter** [comment]
I really like it when the date and time are in the same input field for one big reason: pasteability. It is annoying to have a date/time that you try to copy/paste but have to enter each separate date/time component separately. I think ideally you could just paste in any datetime string into the text field and it would get parsed and re-formatted in the standard format on change. I've done this before where I have an input field that has a datetime that gets submitted to the server and it is then read-in via PHP's `strtotime()`. This makes it nice to enter a string like `+1 minute`. True, this would be a power user feature. We also should be fully parsing the datetime strings in JS without any server-side round trips.

**Comment by aristath** [comment]
> I really like it when the date and time are in the same input field for one big reason: pasteability. It is annoying to have a date/time that you try to copy/paste but have to enter each separate date/time component separately.

huh... I hadn't thought about pasteability... Good point.

> I think ideally you could just paste in any datetime string into the text field and it would get parsed and re-formatted in the standard format on change

I suppose that's possible, but again there are 2 ways to handle this:

* Client-side: We'd have to use JS by including a library like https://github.com/jquery/globalize (IMO WP Core should include it anyway, but I understand the need to properly screen and scrutinize everything that goes in core, so I'm thinking that perhaps not everyone would be open to an idea like that.
* Server-side: Using PHP this is going to be pretty simpler that if we use JS. The downside is that `postMessage` is probably out of the question if we do that, unless we use partial refreshes for the preview.

> I've done this before where I have an input field that has a datetime that gets submitted to the server and it is then read-in via PHP's `strtotime()`. This makes it nice to enter a string like `+1 minute`.

Agreed, that would be pretty awesome! but that would be easier to do using PHP that using JS

> We also should be fully parsing the datetime strings in JS without any server-side round trips.

And this is where things get a bit complicated... We'd either have to write our own implementation for parsing date/time, or include something like http://momentjs.com/ or globalize.

**Comment by valendesigns** [comment]
Shouldn't we __not__ reinvent the wheel here and simply use the same UI WordPress already has, which fits into our size constraints?

![change-post-date-expanded](https://cloud.githubusercontent.com/assets/62798/14126661/7fb31630-f5c7-11e5-82ef-a1762bcab6b8.jpg)

**Comment by westonruter** [comment]
I really dislike the Core UI :frowning: But I realize that is a subjective statement.

**Comment by valendesigns** [comment]
I don't like it either. However, for numerous reasons it would be much simpler to implement a consistent UI rather than baking our own.

**Comment by aristath** [comment]
On the other hand, this is an opportunity to improve things... If the objective is to simply get it done then yeah, this discussion is completely unnecessary and meaningless. We can do it using a dropdown and 4 textfields like core.
But shouldn't we try to improve things? Who knows, maybe if we do it right, core will change. It's not easy, but not impossible either.
And since everyone agrees that core is ugly, change is inevitable. Maybe not now, but it will definitely happen.

**Comment by valendesigns** [comment]
I think it's a lot of effort for a UI enhancement that has many gotchas. Shouldn't we first focus on making it work like Core before we make it pretty?

**Comment by westonruter** [comment]
Yeah, I suppose so. Good on you for keeping us on track, no matter how much
it grieves my heart ;-) That being said, I think a better UI should also
continue to be explored as an enhancement to what core does.

**Comment by valendesigns** [comment]
__I fully agree__! I'm not here to end the discussion of potential paths forward, rather to focus us on making strides towards an MVP. I fully want there to be a date and time picker, I just also want to be pragmatic with what we have resources for and limit our exposure to 3rd party scripts not already in Core since historically Core does not like adding them.

**Comment by westonruter** [comment]
So let's settle on using the Core UI for picking a date as presented on the post edit screen for the initial implementation.

How should we go about previewing? At the simplest, a preview could result in the preview reloading with the `post_date`/`post_date_gmt` overridden. This should ensure the post date appears as expected in the template. However, this isn't probably very helpful in terms of what a user would want to preview for a date change. I think normally a date is changed to cause a post to appear in a different order in a post list. That being the case, perhaps any `WP_Query` instances that could apply to the post should have their `the_posts` filtered to re-sort if the query vars would apply to the post being edited? This should result in the post being re-ordered as expected, as if MySQL had returned that ordered result. As such, implementing selective refresh seems impractical for date changes.

**Comment by valendesigns** [comment]
That sounds very similar to what I was doing for future posts in the Customizer for News and I agree selecting refresh would be impractical here. It does require a reflow of the post order in the archive. However, we could do selective refresh in the context of a single post to update the UI only.

**Comment by westonruter** [comment]
@valendesigns Great point. If `is_singular()` and `get_queried_object_id()` matches the post being edited, then a partial could be refreshed, specifically the `content` part identified by the `post_class()`, per #36.

**Comment by westonruter** [comment]
Implementation here is closely related to #40. Changes to the post date should trigger a full refresh.

**Comment by westonruter** [comment]
Important to note how the post date and modified dates relate here, and in the context of inserted auto-drafts: https://github.com/xwp/wp-customize-posts/pull/152/commits/d154e2203b028fcb4aa646ee087daa9a65532e83

It may be desired that a post date for an inserted post always have NOW as the publish time, as opposed to the time that the auto-draft was created.

**Comment by westonruter** [comment]
In `\WP_Customize_Posts_Preview::get_post_field_partial_schema()`, the `post_date` should be added with just `'fallback_refresh' => true`
