### ISSUE TITLE
Fix Jetpack Contact Form Integration

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#78]
Clicking the “Add Contact Form” has no effect:

<img width="619" alt="customize__demo_xwp_site__ _just_another_wordpress_site" src="https://cloud.githubusercontent.com/assets/134745/14194751/933a8e5e-f766-11e5-81aa-6008f041a0c5.png">

It could be another z-index problem, as fixed in #69.

**Comment by valendesigns** [comment]
Does that button add a shortcode or open a popup?

**Comment by westonruter** [comment]
Modal with `z-index` of `100050`. I'm 99% sure this will be fixed by bumping the `#TB_overlay` and `#TB_window` to `500050`.

**Comment by westonruter** [comment]
Yes! This fixes it:

```diff
diff --git a/css/customize-posts.css b/css/customize-posts.css
index ab63c55..7370759 100644
--- a/css/customize-posts.css
+++ b/css/customize-posts.css
@@ -83,4 +83,8 @@ body:not( .customize-posts-content-editor-pane-open ) div.mce-fullscreen {
 .wp-customizer #wp_editbtns,
 .wp-customizer #wp_gallerybtns {
 	z-index: 500020; /* originally 100020, but z-index of .wp-full-overlay is 500000 */
+}
+.wp-customizer #TB_overlay,
+.wp-customizer #TB_window {
+	z-index: 500050;
 }
```
