### ISSUE TITLE
Media buttons are inaccessible when editor is expanded

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#80]
Good:

<img width="576" alt="dfw-off" src="https://cloud.githubusercontent.com/assets/134745/14198451/21644bd4-f78f-11e5-82b3-68628fb3ed3b.png">

Bad:

<img width="742" alt="dfw-on" src="https://cloud.githubusercontent.com/assets/134745/14198454/24f19090-f78f-11e5-964e-154c6beca91d.png">

**Comment by danagle** [comment]
The 'Add Media' button is visible now. Just tested it with WordPress 4.5:

![add-media-button-visible](https://cloud.githubusercontent.com/assets/752694/14683816/abcfd21c-0724-11e6-8914-729326542e46.jpg)

**Comment by westonruter** [comment]
@danagle Did you try clicking the full screen button?

**Comment by danagle** [comment]
Yes the full screen button also works.

![full-screen-button](https://cloud.githubusercontent.com/assets/752694/14704780/4242f98e-07ae-11e6-96ca-4457b05e7fb8.jpg)

**Comment by westonruter** [comment]
@danagle the problem is that the Add Media button is not visible when the full screen mode is enabled.

**Comment by valendesigns** [comment]
I'm going to work on this today.

**Comment by valendesigns** [comment]
I've fixed the visibility of the media buttons, but there is still an issue when you click "Add Media" nothing happens in either mode. This needs to be addressed in a separate ticket.
