### ISSUE TITLE
Add page template setting and control 

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#85]
Depends on #1.

**Comment by mehigh** [comment]
Hey @westonruter - if there's anything me or @delawski can help on this task, let us know and we'll try to pour in some time from ourselves as well.

**Comment by westonruter** [comment]
Thanks! I am in the middle of #1 which will make this one very simple to implement. I may implement it as part of #1, as the first example implementation.

**Comment by westonruter** [comment]
Here's my work in progress: https://github.com/xwp/wp-customize-posts/issues/89

**Comment by westonruter** [comment]
@mehigh @delawski please give https://github.com/xwp/wp-customize-posts/pull/89 at try!
